### ISSUE TITLE
Exporting count matrix

### ISSUE THREAD

**Issue by hyunhwaj** [tlnagy/Crispulator.jl#48]
Hello, 

I am wondering how I can export the count matrix which is derived from the input parameters. I just only able to have the values of screening performance of the given simulated study as the output of Crispulator. Are you providing any output/function which reveals the count matrix of each sample? If it is not then could you advise me to implement the function?

Thank you,

**Comment by tlnagy** [comment]
Could you clarify what you mean by the count matrix?

**Comment by hyunhwaj** [comment]
Oh sorry, I would explain it clearly. Crispulator simulates the deep sequencing, and we can have read numbers of each sgRNA for low/high reporter bin. I want to have the read numbers once I run the tool, and I called it count matrix because we can have the sgRNA read numbers for each bin with the form of n x 2 matrix (n is the number of sgRNA, and columns are for low/high bin). I hope I clarify it well.

Thank you

**Comment by tlnagy** [comment]
Sorry for not getting back to you sooner. Crispulator does generate your count matrix, but doesn't export it currently. It should be relatively easy to add.

**Comment by hyunhwaj** [comment]
Hello @tlnagy, 

I recently realized that you provide the `bc_counts` data frame, and it stores counts of each sgRNA from the high-throughput sequencing. Therefore, I think you don't have to add any additional function or script. Please correct me if I am wrong or close this issue if it is otherwise. I thank you for your attention to this request and I congratulate your recent publication of this great tool in the journal!

Thank you,

**Comment by tlnagy** [comment]
Let me know if `bc_counts` worked for you! If not, please open a new issue. I'm going to add an example to the docs based on your example in #52. I think it should help others in the future!

**Comment by hyunhwaj** [comment]
I think it is a kind of okay if I want to build single counts for each group. However, I'd like to have any idea how to build the matrix under below conditions:

* Generate another `bc_counts` of un/pre-sorted cells with keeping counts of the high and low.
* Generate multiple replicates under the same configuration, I did it before, but not 100% sure my method is correct.

Thank you,

Hyun-Hwan Jeong

**Comment by tlnagy** [comment]
> Generate another bc_counts of un/pre-sorted cells with keeping counts of the high and low.

Are you simulating a FACS Screen?

**Comment by hyunhwaj** [comment]
> Are you simulating a FACS Screen?

Yes, for the case.

**Comment by tlnagy** [comment]
> Generate another bc_counts of un/pre-sorted cells with keeping counts of the high and low.

I realized that `obs_phenotype` was supposed to serve this purpose so I reverted the previous commit that deleted it. I fleshed out the docs further. http://tamasnagy.com/Crispulator.jl/latest/custom.html#Performing-the-screen-1 should help you with getting the observed phenotype, i.e. the phenotype on which the cells were sorted with FACS

**Comment by tlnagy** [comment]
I see what you want. So I've had to rearchitect `differences_between_bins` to support this approach. It's almost ready. I'll push a PR once I'm done.

**Comment by hyunhwaj** [comment]
I appreciate your support!

Kind Regards,

Hyun-Hwan Jeong

**Comment by tlnagy** [comment]
Hey @hyunhwaj, if you get a chance can you check out the notebook in #53? It has the Unsorted, GFP_low, GFP_high bins that you were looking for. Let me know over there if it works for you.

You should be able to check it out using

```sh
git fetch origin pull/53/head:add-multibin-support
git checkout add-multibin-support
```

**Comment by tlnagy** [comment]
I merged #53 into master so now you should be able to run

```julia
Pkg.checkout("Crispulator")
```

to give it a spin. Please open a new issue if you run into any issues or have suggestions!

**Comment by hyunhwaj** [comment]
That's actually what I've wanted! I checked the notebook, and this ran without any problem.  I truly appreciate your work.

Hyun-Hwan Jeong

**Comment by tlnagy** [comment]
Thanks! Let me know if you need anything else.
