### ISSUE TITLE
"-Inf" values of obs_phenotype

### ISSUE THREAD

**Issue by hyunhwaj** [tlnagy/Crispulator.jl#52]
To simulate growth screening, I wrote below notebook:

https://gist.github.com/hyunhwaj/b941b84224d22b9b4bc112ee3b904d38

After I ran `differences_between_bins`, I am able to have `bc_counts` variable, but all of the values of `obs_phenotype` are `-Inf`. I don't see the issue when I simulate FACS screening. I am doubting the `-Inf` values are correct, and we might have other values which are close to `theo_phenotype`. Also, it is possible my code on the notebook is wrong. I will appreciate if it is true and you inform me what mistakes were in the code.

Thank you,

Hyun-Hwan Jeong

**Comment by tlnagy** [comment]
Sorry it took me so long to get to this. `obs_phenotype` is only used for FACS screens so it shouldn't be a problem for a Growth Screen. 

`obs_phenotype` is initialized to `-Inf` here

https://github.com/tlnagy/Crispulator.jl/blob/master/src/simulation/common.jl#L32

and then is updated when you call `select` 

https://github.com/tlnagy/Crispulator.jl/blob/master/src/simulation/selection.jl#L19-L20

**Comment by tlnagy** [comment]
After looking at this, it looks like `obs_phenotype` is a bit unnecessary since the "observed" phenotype is the counts of the guide in either bin. There is actual no reference to `obs_phenotype` outside of the two lines in the previous commit.

**Comment by tlnagy** [comment]
Also, @hyunhwaj. Sometimes running your first three blocks of code (cells), gives the following the following error:

```julia
ArgumentError: median of an empty array is undefined, Float64[]

Stacktrace:
 [1] median!(::Array{Float64,1}) at ./statistics.jl:590
 [2] median(::DataArrays.DataArray{Float64,1}) at /Users/tamasnagy/.julia/v0.6/DataArrays/src/operators.jl:651
 [3] #differences_between_bins#80(::Symbol, ::Symbol, ::Function, ::Dict{Symbol,DataFrames.DataFrame}) at /Users/tamasnagy/.julia/v0.6/Crispulator/src/simulation/processing.jl:13
 [4] differences_between_bins(::Dict{Symbol,DataFrames.DataFrame}) at /Users/tamasnagy/.julia/v0.6/Crispulator/src/simulation/processing.jl:5
 [5] include_string(::String, ::String) at ./loading.jl:522
```

This is because you're only simulated 10 genes and sometimes there's no negative control guides (since you set their frequency at 5%). 

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1661487/35940554-6eb5a06e-0c04-11e8-8123-41de55ed35b6.png">

If this happens, I recommend just rerunning till there is a negative control or increase the frequency of negative controls or increase the total number of genes.

**Comment by hyunhwaj** [comment]
Thanks, @tlnagy for your detailed answers regarding my question. I have further questions:

1. Did you mean that `obs_phenotype` is no longer need to be in the `bc_counts` anymore for both types of screens?
2. I want to make sure `max_phenotype_dists` is the parameter to set up proportions number of genes for each type of phenotype randomly. Am I understanding correctly? 
3. Does any **negative control genes** has to be in the simulation? If it is, then could you briefly explain any reason why it has to be in the simulation?

Thanks again,

Hyun-Hwan Jeong
